---
name: Pull request verification

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        working-directory: ui
        run: npm install

      - name: Run lint
        working-directory: ui
        run: npm run lint

      - name: Build the project
        working-directory: ui
        run: npm run build
